### PR TITLE
unmarked as private

### PR DESCRIPTION
**Pull request by marcus7777**

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
Hi @marcus7777, these repos are marked as private because we don't want them published in the bower's registry for the time being. Closing this.

**Comment by marcus7777** [comment]
https://blog.polymer-project.org/announcements/2016/02/16/2016-roadmap/
...
Goals:

Accelerate Polymer + Community engagement
Tighten the core Polymer team and community feedback loop - better evolve Polymer as the community evolves
Publish all elements to npm and bower
...

**Comment by valdrinkoshi** [comment]
https://github.com/PolymerElements/paper-button/issues/104#issuecomment-184809749
Also, save yourself and us review time by using https://github.com/PolymerLabs/tedium instead of opening 24 PRs ;)

**Comment by marcus7777** [comment]
https://blog.polymer-project.org/announcements/2016/02/16/2016-roadmap/
...
Goals:

Accelerate Polymer + Community engagement
Tighten the core Polymer team and community feedback loop - better evolve Polymer as the community evolves
Publish all elements to npm and bower
...

**Comment by notwaldorf** [comment]
@marcus7777 Hiya! Please stop spamming the issues with the same comment. We understand what you meant, but as @keanulee answered you in `paper-button` (linked by @valdrinkoshi above), we simply can't flip the flag like this. We would like to publish these elements to bower, but some of our element names are already taken (like `paper-ripple`, for example), which means _we_ can't publish our `paper-ripple` there. We are working on figuring out a solution, but in the meantime, this is what it is.

Also, as @valdrinkoshi mentioned, in the future please don't copy paste the same answer 24 times. `tedium` is our bot for doing the same thing many times, and an issue there would have been sufficient. Right now one of our team members has to individually close each of these PRs, which is time consuming.

Thanks! 🍰

**Comment by marcus7777** [comment]
okay 
sorry
Thanks! 🍰

**Pull request closed without merging**
