### PR TITLE
fixed ensure target

### PR DESCRIPTION
**Pull request by fincha**
fix for #63

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
This would work only in Shady DOM, not with native Shadow DOM. 
The proper way to support this would be to either support dynamic changes of `dialogElement` (meaning have an observer and update accordingly to new and old value) or traverse the parents until we find a good dialog element candidate.

**Comment by fincha** [comment]
@valdrinkoshi one of my colleges suggested to use this.async, that do you with, will this solve this problem?

**Comment by valdrinkoshi** [comment]
I think we need an observer for changes of `dialogElement`, and ensure we have a value for `dialogElement` on attached. I'll open a new PR to address this 👌

**Comment by valdrinkoshi** [comment]
Fixing this in #69, added tests too 👌

**Pull request closed without merging**
